events {}

http {
  resolver 8.8.8.8;

  server {
    listen 80;

    server_name lpintomba.itsgusta.com;

    location = /gtm.js {
      proxy_pass https://www.googletagmanager.com/gtm.js$is_args$args;

      proxy_set_header Host www.googletagmanager.com;
      proxy_ssl_server_name on;
    }
  }
}
